version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ecommerce-postgres
    environment:
      TZ: Asia/Ho_Chi_Minh
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ecommerce
    command:
      - "postgres"
      - "-c"
      - "timezone=Asia/Ho_Chi_Minh"
      - "-c"
      - "log_timezone=Asia/Ho_Chi_Minh"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ecommerce"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
